CREATE TABLE binanceapibd.bin_tbl_crypto_raw(
	tcr_record_id                            BIGINT       NOT NULL AUTO_INCREMENT,
	tcr_symbol_name                          VARCHAR(100) NOT NULL,
	tcr_status                               VARCHAR(50 ) NOT NULL,
    tcr_baseAsset                            VARCHAR(50 ) NOT NULL,
    tcr_baseAssetPrecision                   INT          NOT NULL,
    tcr_quoteAsset                           VARCHAR(50 ) NOT NULL,
    tcr_quotePrecision                       INT          NOT NULL,
    tcr_quoteAssetPrecision                  INT          NOT NULL,
    tcr_baseCommissionPrecision              INT          NOT NULL,
    tcr_quoteCommissionPrecision             INT          NOT NULL,
    tcr_icebergAllowed                       BOOLEAN      NOT NULL,
    tcr_ocoAllowed                           BOOLEAN      NOT NULL,
    tcr_quoteOrderQtyMarketAllowed           BOOLEAN      NOT NULL,
    tcr_isSpotTradingAllowed                 BOOLEAN      NOT NULL,
    tcr_isMarginTradingAllowed               BOOLEAN      NOT NULL,
    tcr_requestDate                          DATE         NOT NULL,
    tcr_price                                DECIMAL      NOT NULL,
    tcr_bidPrice_x                           DECIMAL      NOT NULL,
    tcr_bidQty_x                             DECIMAL      NOT NULL,
    tcr_askPrice_x                           DECIMAL      NOT NULL,
    tcr_askQty_x                             DECIMAL      NOT NULL,
    tcr_priceChange                          DECIMAL      NOT NULL,
    tcr_priceChangePercent                   DECIMAL      NOT NULL,
    tcr_weightedAvgPrice                     DECIMAL      NOT NULL,
    tcr_prevClosePrice                       DECIMAL      NOT NULL,
    tcr_lastPrice                            DECIMAL      NOT NULL,
    tcr_lastQty                              DECIMAL      NOT NULL,
    tcr_bidPrice_y                           DECIMAL      NOT NULL,
    tcr_bidQty_y                             DECIMAL      NOT NULL,
    tcr_askPrice_y                           DECIMAL      NOT NULL,
    tcr_askQty_y                             DECIMAL      NOT NULL,
    tcr_openPrice                            DECIMAL      NOT NULL,
    tcr_highPrice                            DECIMAL      NOT NULL,
    tcr_lowPrice                             DECIMAL      NOT NULL,
    tcr_volume                               DECIMAL      NOT NULL,
    tcr_quoteVolume                          DECIMAL      NOT NULL,
    tcr_openTime                             DECIMAL      NOT NULL,
    tcr_closeTime                            DECIMAL      NOT NULL,
    tcr_firstId                              DECIMAL      NOT NULL,
    tcr_lastId                               DECIMAL      NOT NULL,
    tcr_count                                BIGINT       NOT NULL,
    tcr_procces_id                           VARCHAR(100) NOT NULL,
    tcr_process_date                         DATETIME     DEFAULT CURRENT_TIMESTAMP,  
    tcr_update_date                          DATETIME     ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (tcr_record_id)
);